(function () {
  'use strict';
  var app = document.getElementById('app');
  var $ = function (s) { return document.querySelector(s); };
  var cfg = window.SITE_CONFIG || {};
  var B = window.__BUNDLE__;

  function fail(msg) { app.innerHTML = '<div class="warn" dir="auto">' + msg + '</div>'; }
  if (!B) { fail('فایل <b>content/bundle.js</b> پیدا نشد. این فایل را GitHub Action به‌صورت خودکار می‌سازد؛ یا دستور <code>node tools/build.js</code> را اجرا کنید. <br>content/bundle.js not found. It is generated by the GitHub Action (or run <code>node tools/build.js</code>).'); return; }

  /* ---------- load content ---------- */
  var cl = Parser.parseClusters(B.clusters);
  var rf = Parser.parseRefs(B.references);
  var topics = [], problems = cl.errors.concat(rf.errors);
  Object.keys(B.topics).sort().forEach(function (f) {
    var r = Parser.parseTopic(B.topics[f], f);
    problems = problems.concat(r.errors);
    if (r.topic) topics.push(r.topic);
  });
  var store = Render.makeStore(cl.clusters, topics, rf.refs);
  problems = problems.concat(Parser.validate(topics, cl.clusters, rf.refs));
  if (problems.length && window.console) console.warn('Content problems:\n' + problems.join('\n'));

  /* ---------- routing ---------- */
  function route() {
    var hs = location.hash || '#/', m;
    if ((m = hs.match(/^#\/v\/([a-z0-9\-]+)$/))) {
      var r = Render.renderVariant(store, m[1]);
      if (r) { app.innerHTML = r.html; document.title = r.title; window.scrollTo(0, 0); return; }
    } else if ((m = hs.match(/^#\/t\/([a-z0-9\-]+)$/))) {
      var r2 = Render.renderTopic(store, m[1]);
      if (r2) { app.innerHTML = r2.html; document.title = r2.title; window.scrollTo(0, 0); return; }
    }
    app.innerHTML = Render.renderIndex(store, $('#q').value);
    document.title = 'دستورات اورژانس · Emergency Orders';
    if (!hs.match(/^#c-/)) window.scrollTo(0, 0);
  }
  window.addEventListener('hashchange', route);

  document.addEventListener('click', function (e) {
    var a = e.target.closest && e.target.closest('a[data-jump]');
    if (a) {
      e.preventDefault();
      var id = 'c-' + a.dataset.jump, el = document.getElementById(id);
      if (el) el.scrollIntoView();
      else { location.hash = '#/'; setTimeout(function () { var x = document.getElementById(id); if (x) x.scrollIntoView(); }, 0); }
      return;
    }
    var b = e.target.closest && e.target.closest('button[data-send]');
    if (b) sendComment(b.closest('.comment'), b);
  });
  $('#q').addEventListener('input', function () {
    if (!/^#\/?$|^$/.test(location.hash)) location.hash = '#/';
    else app.innerHTML = Render.renderIndex(store, $('#q').value);
  });
  $('#theme').addEventListener('click', function () {
    var r = document.documentElement, cur = r.getAttribute('data-theme');
    var dark = cur ? cur === 'dark' : matchMedia('(prefers-color-scheme:dark)').matches;
    r.setAttribute('data-theme', dark ? 'light' : 'dark');
  });

  /* ---------- feedback box ---------- */
  function repoSlug() {
    if (cfg.repo) return cfg.repo;
    var h = location.hostname, p = location.pathname.split('/').filter(Boolean);
    if (/\.github\.io$/.test(h)) return h.replace(/\.github\.io$/, '') + '/' + (p[0] || h);
    return '';
  }
  function sendComment(box, btn) {
    var ta = box.querySelector('textarea'), nm = box.querySelector('input'), msg = box.querySelector('.cmsg');
    var text = ta.value.trim();
    if (!text) { msg.textContent = 'لطفاً نظر خود را بنویسید. · Please write a comment.'; return; }
    var data = { page: box.dataset.page, title: box.dataset.title, url: location.href, name: nm.value.trim(), comment: text, time: new Date().toISOString() };
    if (cfg.commentEndpoint) {
      btn.disabled = true;
      var body = new URLSearchParams(data).toString();
      fetch(cfg.commentEndpoint, { method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: body })
        .then(function () { ta.value = ''; msg.textContent = 'ممنون! نظر شما ثبت شد. · Thank you, your comment was saved.'; })
        .catch(function () { msg.textContent = 'ارسال نشد؛ اتصال را بررسی کنید. · Could not send; check your connection.'; })
        .then(function () { btn.disabled = false; });
      return;
    }
    var slug = repoSlug();
    if (!slug) { msg.textContent = 'ارسال نظر هنوز تنظیم نشده است (config.js). · Feedback is not configured yet (config.js).'; return; }
    var title = '[Feedback] ' + data.title;
    var bodyMd = data.comment + '\n\n---\nPage: ' + data.page + '\nURL: ' + data.url + (data.name ? '\nName: ' + data.name : '') + '\nTime: ' + data.time;
    var url = 'https://github.com/' + slug + '/issues/new?labels=feedback&title=' + encodeURIComponent(title) + '&body=' + encodeURIComponent(bodyMd);
    window.open(url, '_blank', 'noopener');
    msg.textContent = 'صفحه GitHub باز شد؛ روی «Submit new issue» بزنید. · A GitHub page opened. Press “Submit new issue”.';
  }

  /* ---------- footer, offline ---------- */
  $('#foot').innerHTML = '<div dir="rtl" style="font-family:var(--fa-font)">منابع: <b>A</b> = برگه دستورات پزشک، مرکز آموزشی درمانی بعثت (دانشگاه علوم پزشکی همدان). <b>B</b> = «کتابچه دستورات شایع در اورژانس»، گروه طب اورژانس دانشگاه علوم پزشکی اصفهان، زمستان ۱۳۹۸ (بر پایه Rosen 2018). سناریوها نمونه‌های آموزشی ساخته‌شده برای این صفحه‌اند. شماره‌های داخل [ ] به فهرست مراجع پایین هر صفحه اشاره دارند.</div><div dir="ltr" style="margin-top:6px">Sources: <b>A</b> = Physician Orders Sheet handout, Beesat center (Hamadan Univ. of Medical Sciences). <b>B</b> = “Common Emergency Orders” booklet, Isfahan Univ. of Medical Sciences, Winter 1398 (based on Rosen 2018). Scenarios are illustrative teaching cases. Numbered [ ] items point to the references at the bottom of each page.</div>' + (B.generated ? '<div class="mute" dir="ltr" style="margin-top:6px">Content built: ' + B.generated + '</div>' : '');
  route();
  if ('serviceWorker' in navigator && /^https?:$/.test(location.protocol)) {
    navigator.serviceWorker.register('sw.js').catch(function () {});
  }
})();
