#!/usr/bin/env node
/* Validates content/ and builds content/bundle.js.
 *   node tools/build.js          validate + write content/bundle.js
 *   node tools/build.js --check  validate only
 * Exit code 1 if anything is wrong (valid topics are still written to the bundle). */
'use strict';
const fs = require('fs');
const path = require('path');
const Parser = require('../js/parser.js');

const root = path.join(__dirname, '..');
const dir = path.join(root, 'content');
const check = process.argv.includes('--check');
const read = (f) => fs.readFileSync(path.join(dir, f), 'utf8');

const clustersText = read('clusters.txt');
const refsText = read('references.md');
const cl = Parser.parseClusters(clustersText);
const rf = Parser.parseRefs(refsText);
let errors = cl.errors.concat(rf.errors);

const files = fs.readdirSync(path.join(dir, 'topics')).filter((f) => f.endsWith('.md') && !f.startsWith('_')).sort();
const topics = [], bundleTopics = {};
files.forEach((f) => {
  const text = fs.readFileSync(path.join(dir, 'topics', f), 'utf8');
  const r = Parser.parseTopic(text, f);
  errors = errors.concat(r.errors);
  if (r.topic) { topics.push(r.topic); if (!r.errors.length) bundleTopics[f] = text; }
});
errors = errors.concat(Parser.validate(topics, cl.clusters, rf.refs));

const nv = topics.reduce((n, t) => n + t.variants.length, 0);
console.log(`${files.length} topic files, ${topics.length} topics, ${nv} variants, ${Object.keys(rf.refs).length} references.`);
if (errors.length) { console.error('\nPROBLEMS FOUND:\n - ' + errors.join('\n - ')); }
else console.log('All checks passed.');

if (!check) {
  const bundle = { generated: new Date().toISOString().slice(0, 10), clusters: clustersText, references: refsText, topics: bundleTopics };
  const js = '/* Generated by tools/build.js. Do not edit. */\nwindow.__BUNDLE__ = ' + JSON.stringify(bundle).split(String.fromCharCode(0x2028)).join('\\u2028').split(String.fromCharCode(0x2029)).join('\\u2029') + ';\n';
  fs.writeFileSync(path.join(dir, 'bundle.js'), js);
  console.log('Wrote content/bundle.js (' + Math.round(js.length / 1024) + ' KB).');
}
process.exit(errors.length ? 1 : 0);
